const verbs = [
    'alchemize',
    'annihilate',
    'asphyxiate',
    'assassinate',
    'ax',
    'backstab',
    'barrage',
    'bash',
    'bite',
    'black out',
    'blind',
    'blot out',
    'blue pencil',
    'body slam',
    'bog',
    'bump off',
    'burn',
    'butcher',
    'cancel',
    'chill',
    'choke',
    'claw',
    'cleave',
    'combust',
    'conclude',
    'cover',
    'crucify',
    'cut',
    'cut off',
    'decay',
    'defeat',
    'deflect',
    'defragment',
    'delete',
    'destroy',
    'disarm',
    'dispatch',
    'do',
    'do away with',
    'do in',
    'double tap',
    'doubt',
    'down',
    'dropkick',
    'drown',
    'dualcast',
    'dump',
    'efface',
    'electrocute',
    'eliminate',
    'envenom',
    'eradicate',
    'erase',
    'evaluate',
    'eviscerate',
    'execute',
    'exhume',
    'expunge',
    'exterminate',
    'extirpate',
    'finish',
    'finish off',
    'garrote',
    'get',
    'guillotine',
    'gun down',
    'halt',
    'hang',
    'headbutt',
    'hit',
    'hyperbeam',
    'immolate',
    'intimidate',
    'jilt',
    'kill',
    'knock off',
    'knock off ',
    'knock out',
    'KO',
    'leap',
    'leg sweep',
    'level',
    'liquidate',
    'lynch',
    'mark out',
    'massacre',
    'murder',
    'neutralize',
    'nix',
    'obliterate',
    'obscure',
    'off',
    'outmanouver',
    'poison',
    'polish off',
    'prostrate',
    'pummel',
    'put away',
    'quick slash',
    'rage against',
    'ravage',
    'recycle',
    'regret',
    'reprogram',
    'root out',
    'rub off',
    'rub out',
    'rub out ',
    'rupture',
    'sacrifice',
    'scrape',
    'scratch',
    'scrub',
    'shame',
    'shiv',
    'shoot down',
    'sink',
    'skewer',
    'slaughter',
    'slay',
    'slice',
    'smash',
    'smite',
    'smother',
    'snuff',
    'squash',
    'storm',
    'strangle',
    'strike',
    'study',
    'sucker punch',
    'suffocate',
    'sunder',
    'take apart',
    'take out',
    'torpedo',
    'total',
    'trash',
    'trip',
    'twin strike',
    'uppercut',
    'vault',
    'void',
    'wallop',
    'wash out',
    'waste',
    'weave',
    'wheel kick',
    'wild strike',
    'wipe out',
    'wound',
    'X-out',
    'zap',
];

const nouns = [
    'abode',
    'accommodation',
    'apartment',
    'belfry',
    'building',
    'castle',
    'cave',
    'citadel',
    'column',
    'condo',
    'condominium',
    'construction',
    'crib',
    'den',
    'domicile',
    'dwelling',
    'edifice',
    'erection',
    'establishment',
    'flat',
    'flophouse',
    'flèche',
    'fort',
    'fortress',
    'habitation',
    'hall',
    'headquarters',
    'high rise',
    'home',
    'homestead',
    'house',
    'household',
    'hut',
    'inhabitancy',
    'inhabitation',
    'joint',
    'keep',
    'kennel',
    'living quarters',
    'lodging',
    'lookout',
    'manor',
    'mansion',
    'mast',
    'minaret',
    'monolith',
    'obelisk',
    'pad',
    'palace',
    'penthouse',
    'pile',
    'pillar',
    'place',
    'premises',
    'property',
    'rental',
    'residence',
    'residency',
    'roof',
    'seat',
    'settlement',
    'shack',
    'shikara',
    'skyscraper',
    'spire',
    'steeple',
    'stronghold',
    'structure',
    'suite',
    'superstructure',
    'tower',
    'turf',
    'turret',
    'villa',
    'ziggurat'
];

module.exports = {
    verbs,
    nouns
}