const verbs = [
    'annihilate',
    'asphyxiate',
    'assassinate',
    'ax',
    'black out',
    'blot out',
    'blue pencil',
    'bog',
    'bump off',
    'butcher',
    'cancel',
    'cover',
    'crucify',
    'cut',
    'cut off',
    'defeat',
    'delete',
    'destroy',
    'dispatch',
    'do',
    'do away with',
    'do in',
    'down',
    'drown',
    'dump',
    'efface',
    'electrocute',
    'eliminate',
    'eradicate',
    'erase',
    'execute',
    'expunge',
    'exterminate',
    'extirpate',
    'finish',
    'finish off',
    'garrote',
    'get',
    'guillotine',
    'gun down',
    'hang',
    'hit',
    'immolate',
    'kill',
    'knock off',
    'knock off ',
    'knock out',
    'KO',
    'level',
    'liquidate',
    'lynch',
    'mark out',
    'massacre',
    'murder',
    'neutralize',
    'nix',
    'obliterate',
    'obscure',
    'off',
    'poison',
    'polish off',
    'put away',
    'put to death',
    'ravage',
    'root out',
    'rub off',
    'rub out',
    'rub out ',
    'sacrifice',
    'scratch',
    'scrub',
    'shoot down',
    'sink',
    'slaughter',
    'slay',
    'smash',
    'smother',
    'snuff',
    'squash',
    'strangle',
    'suffocate',
    'take apart',
    'take out',
    'torpedo',
    'total',
    'trash',
    'wash out',
    'waste',
    'wipe out',
    'X-out',
    'zap',
];

const nouns = [
    'abode',
    'accommodation',
    'apartment',
    'belfry',
    'building',
    'castle',
    'cave',
    'citadel',
    'column',
    'condo',
    'condominium',
    'construction',
    'crib',
    'den',
    'domicile',
    'dwelling',
    'edifice',
    'erection',
    'establishment',
    'flat',
    'flophouse',
    'flèche',
    'fort',
    'fortress',
    'habitation',
    'hall',
    'headquarters',
    'high rise ',
    'home',
    'homestead',
    'house',
    'household',
    'hut',
    'inhabitancy',
    'inhabitation',
    'joint',
    'keep',
    'kennel',
    'living quarters ',
    'lodging',
    'lookout',
    'manor',
    'mansion',
    'mast',
    'minaret',
    'monolith',
    'obelisk',
    'pad',
    'palace',
    'penthouse',
    'pile',
    'pillar',
    'place',
    'premises',
    'property',
    'rental',
    'residence',
    'residency',
    'roof',
    'seat',
    'settlement',
    'shack',
    'shikara',
    'skyscraper',
    'spire',
    'steeple',
    'stronghold',
    'structure',
    'suite',
    'superstructure',
    'turf',
    'turret',
    'villa',
    'ziggurat'
];

module.exports = {
    verbs,
    nouns
}